import "./globals.css";
import { inter } from "./fonts";
import Image from "next/image";

/* ICONS */
import ApplicationIcons from "../icons/ApplicationIcons";

/* COMPONENTS */
import Hexagon from "../components/Hexagon";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <header className="main-header">
          <Image
            src="/images/logo.png"
            alt="Spybee Logo"
            width={150}
            height={50}
          />
          <div className="user-info">
            <Hexagon>
              <ApplicationIcons iconName="usericon" />
            </Hexagon>
            <p className="text-md font-medium">
              Sebas <br />
              <span className="text-sm font-light">Administrador</span>
            </p>
            <button>
              <ApplicationIcons iconName="arrowicon" direction="bottom" />
            </button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
